# Generated by Django 5.1.3 on 2025-02-13 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('categoryName', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('deptName', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('roleName', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('courseName', models.CharField(max_length=15, null=True)),
                ('courseDuration', models.CharField(max_length=15, null=True)),
                ('deptId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
            ],
        ),
    ]
