# Generated by Django 5.1.5 on 2025-03-02 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('categoryName', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('deptName', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('roleName', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('courseName', models.CharField(max_length=15, null=True)),
                ('duration', models.CharField(max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('coardinator', models.CharField(max_length=15, null=True)),
                ('deptId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uniqueId', models.CharField(max_length=20, null=True)),
                ('firstName', models.CharField(max_length=15, null=True)),
                ('lastName', models.CharField(max_length=15, null=True)),
                ('phoneNo', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('password', models.CharField(max_length=256, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='faculty_images/')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=15, null=True)),
                ('lastName', models.CharField(max_length=15, null=True)),
                ('phoneNo', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('password', models.CharField(max_length=256, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='admin_images/')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('enrollmentNo', models.CharField(max_length=20, null=True)),
                ('firstName', models.CharField(max_length=15, null=True)),
                ('lastName', models.CharField(max_length=15, null=True)),
                ('phoneNo', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('division', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='student_images/')),
                ('password', models.CharField(max_length=256, null=True)),
                ('admissionDate', models.DateTimeField(null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='SupportStaff',
            fields=[
                ('staffId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=15, null=True)),
                ('lastName', models.CharField(max_length=15, null=True)),
                ('phoneNo', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('password', models.CharField(max_length=256, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='staff_images/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role')),
            ],
        ),
    ]
