<<<<<<< HEAD
# Generated by Django 5.1.3 on 2025-02-13 05:03

import django.db.models.deletion
=======
# Generated by Django 5.1.5 on 2025-02-12 07:49

>>>>>>> 54149b5d8aaee6e739d162c8910bdee7ef1be5aa
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Category',
            fields=[
                ('categoryId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('categoryName', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('deptName', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('roleName', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('courseName', models.CharField(max_length=15, null=True)),
                ('courseDuration', models.CharField(max_length=15, null=True)),
                ('deptId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
=======
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
>>>>>>> 54149b5d8aaee6e739d162c8910bdee7ef1be5aa
            ],
        ),
    ]
