# Generated by Django 5.1.3 on 2025-02-17 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseDuration',
            new_name='coardinator',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=15, null=True)),
                ('lastName', models.CharField(max_length=15, null=True)),
                ('phoneNo', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('uniqueId', models.IntegerField(null=True)),
                ('firstName', models.CharField(max_length=15, null=True)),
                ('lastName', models.CharField(max_length=15, null=True)),
                ('phoneNo', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('enrollmentNo', models.IntegerField(null=True)),
                ('firstName', models.CharField(max_length=15, null=True)),
                ('lastName', models.CharField(max_length=15, null=True)),
                ('phoneNo', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('division', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('password', models.CharField(max_length=20, null=True)),
                ('admissionDate', models.DateTimeField(null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='SupportStaff',
            fields=[
                ('staffId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('uniqueId', models.IntegerField(null=True)),
                ('firstName', models.CharField(max_length=15, null=True)),
                ('lastName', models.CharField(max_length=15, null=True)),
                ('phoneNo', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role')),
            ],
        ),
    ]
