# Generated by Django 5.1.3 on 2025-02-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_admin_password_alter_faculty_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='deptId',
        ),
        migrations.AddField(
            model_name='department',
            name='courseId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course'),
        ),
    ]
