# Generated by Django 5.1.3 on 2025-02-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_course_deptid_department_courseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='courseId',
        ),
        migrations.AddField(
            model_name='course',
            name='deptId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department'),
        ),
    ]
