# Generated by Django 5.1.3 on 2025-02-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_admin_gender_alter_faculty_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='adminId',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='facultyId',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentId',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='supportstaff',
            name='staffId',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
