# Generated by Django 5.1.3 on 2025-02-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_admin_adminid_alter_faculty_facultyid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportstaff',
            name='uniqueId',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='uniqueId',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollmentNo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
